build:
  version: "3.0"

cards:
  message: "Welcome to MaxxBank cards related local default APIs"
  contactDetails:
    name: "Mahendra Chawla"
    email: "itssmaxx@gmail.com"
  onCallSupport:
    -(91) 99989-79695
    -(91) 95969-79899