server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
   active:
    - "prod"

build:
  version: "3.0"

cards:
  message: "Welcome to MaxxBank cards related local default APIs"
  contactDetails:
    name: "Mahendra Chawla"
    email: "itssmaxx@gmail.com"
  onCallSupport:
    -(91) 99989-79695
    -(91) 95969-79899