services:
  rabbit:
   image: rabbitmq:3.13-management
   hostname: rabbitmq
   ports:
     - "5671:5672"
     - "15671:15672"
   healthcheck:
     test: rabbitmq-diagnostics check_port_connectivity
     interval: 10s
     timeout: 5s
     retries: 10
     start_period: 10s
  configserver:
    image: "maxx26/configserver:S2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fial --silent localhost:8071/actuator/health/readiness | grep UP || exit1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - maxxbank
  accounts:
    image: "maxx26/accounts:S2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - maxxbank
    environment:
      SPRING_APPLICTION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
  loans:
    image: "maxx26/loans:S2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - maxxbank
    environment:
      SPRING_APPLICTION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
  cards:
    image: "maxx26/cards:S2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - maxxbank
    environment:
      SPRING_APPLICTION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
networks:
  maxxbank:
    driver: "bridge"