spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to MaxxBank accounts related local PROD APIs"
  contactDetails:
    name: "Mahendra Chawla - PROD"
    email: "itssmaxx_PROD@gmail.com"
  onCallSupport:
    -(91) 99989-79695
    -(91) 95969-79899