services:
  accounts:
    image: "maxx26/accounts:S1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - maxxbank
  loans:
    image: "maxx26/loans:S1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - maxxbank
  cards:
    image: "maxx26/cards:S1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - maxxbank
networks:
  maxxbank:
    driver: "bridge"