build:
  version: "3.0"
java_home: "17"

accounts:
  message: "Welcome to MaxxBank accounts related local default APIs"
  contactDetails:
    name: "Mahendra Chawla"
    email: "itssmaxx@gmail.com"
  onCallSupport:
    -(91) 99989-79695 
    -(91) 95969-79899
