build:
  version: "1.0"
java_home: "17"

accounts:
  message: "Welcome to MaxxBank accounts related local PROD APIs"
  contactDetails:
    name: "Mahendra Chawla - PROD"
    email: "itssmaxx_PROD@gmail.com"
  onCallSupport:
    -(91) 99989-79695
    -(91) 95969-79899